name: Run Cypress tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install live-server globally
        run: npm install -g live-server

      - name: Start live-server in background
        run: |
          npx live-server --port=5500 --quiet &
          sleep 5

      - name: Run Cypress tests
        run: npx cypress run
