name: Run Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  live-tests:
    name: Run Live Login/Alert Tests
    runs-on: ubuntu-latest

    env:
      CYPRESS_emailAddress: ${{ secrets.emailAddress }}
      CYPRESS_password: ${{ secrets.password }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Live tests
        run: npx cypress run --spec "cypress/e2e/live/*" --config baseUrl=https://live.blacklinesafety.com

  protocol-tests:
    name: Run Protocol Tests (Local HTML App)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run protocol tests with live-server
        run: npm run cy:run:protocol