name: Deploy and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Test PRs and main branch locally (fast & reliable)
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Test locally
        run: |
          npx http-server -p 5500 -c-1 . &
          npx wait-on http://127.0.0.1:5500 --timeout 30000
          npx cypress run --browser chrome --config baseUrl=http://127.0.0.1:5500

  # Deploy main branch (no testing, just deploy)
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test]  # Only deploy if tests pass
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - uses: actions/deploy-pages@v4