name: HTML & JS QA Checks

on:
  push:
    paths:
      - 'automated-basic-non-gas-alert-protocol/**.html'
      - 'automated-basic-non-gas-alert-protocol/**.js'

jobs:
  qa-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tidy
        run: sudo apt-get update && sudo apt-get install -y tidy

      - name: Validate HTML
        run: tidy -errors -q automated-basic-non-gas-alert-protocol/index.html || true

      - name: Check for broken local links
        run: |
          grep -n "href=" automated-basic-non-gas-alert-protocol/*.html | grep -v "http" || true

      - name: Verify critical DOM elements exist
        run: |
          grep -q "alert-protocol" automated-basic-non-gas-alert-protocol/index.html && echo "✅ Protocol structure found" || echo "❌ Missing key structure"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install ESLint
        run: |
          npm init -y
          npm install eslint --save-dev

      - name: Lint JS files
        run: npx eslint automated-basic-non-gas-alert-protocol/*.js || true
